### ISSUE TITLE
hoaxshell is picked up by Defender for Endpoint, alerts are triggered in Sentinel and activity can be audited in Defender 365 as a result

### ISSUE THREAD

**Issue by pr0b3r7** [t3l3machus/hoaxshell#11]
Sentinel Alert: 'A command in PowerShell was executed by a suspicious process. PowerShell is often used by attackers to bypass security protection mechanisms by executing their payload in memory without touching the disk and leaving any trace. An attacker might be executing commands in the system.'

Alerts are on behavior according to Defender 365 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/14915771/189251053-ff98d30a-d013-4ba2-a931-bd663364e95e.png">
<img width="2030" alt="image" src="https://user-images.githubusercontent.com/14915771/189250944-16169615-ee2a-4f91-bb81-ee5fc18cc0c6.png">
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/14915771/189250906-d61fefdb-0f58-4c02-8e90-c2887f5a39c9.png">

Is the undetectable claim for signature based detection?

Thank you

**Comment by t3l3machus** [comment]
Hello @pr0b3r7, and thanks for the info. 
Hoaxshell can generate several payload variations according to the user provided command line arguments. From the small part of the decoded command that is visible in the second screenshot you provided, it seems that you used hoaxshell's https payload without providing a trusted certificate. This particular payload is kind of a red flag, as it begins with an additional block of code that instructs powershell to skip SSL certificate checks, which makes it suspicious and easy to detect. Does the simple, http-based payload produce the same alerts?

When showcasing detection cases it would be much clearer to also provide the command used to generate the payload that got detected. 

My initial objective with hoaxshell was to not get caught by (classic) Defender and mainstream commercial AVs so that i can play harder CTF machines and use it in penetration testings. After some tests i noticed that it does well in hardened environments with Endpoint protection and decided to make it public. The "currently undetected by Microsoft Defender" claim is for signature based detection as well because it was tested and worked against in the past, although, i don't expect it to last. To be honest, I expect to archive this project soon.

**Comment by pr0b3r7** [comment]
Hi @t3l3machus - thank you for the thoughtful response and providing a solution to obtain the desired result - it was very helpful! I have had the chance to test again today and you were right, it was not detected... At all.

I will test more extensively, and hopefully document all results and provide them to you once they're ready. I am very interested in your project and it is presenting a great opportunity for me to learn new things. 

Thank you for your patience and congratulations on the great project!

**Comment by t3l3machus** [comment]
@pr0b3r7 glad to hear it worked and thank you for testing it! This was really helpful :)
I invite you to share similar information in the future, if you come across AV solutions that detect hoaxshell or the opposite.
